export function getBatteryManagementPageHtml(): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Battery Management</title><style>
:root{font-family:system-ui;color:#172033;background:#f5f7fa}*{box-sizing:border-box}body{margin:0}header{background:#fff;border-bottom:1px solid #dce1e8;padding:14px 20px}nav{display:flex;gap:10px;flex-wrap:wrap}nav a,.button{border:0;border-radius:7px;padding:9px 13px;background:#2563eb;color:#fff;text-decoration:none;cursor:pointer}main{max-width:1000px;margin:auto;padding:20px;display:grid;gap:18px}.card{background:#fff;border:1px solid #dce1e8;border-radius:10px;padding:18px}.metrics,.form{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.metric{background:#f8fafc;border-radius:8px;padding:14px}.metric strong{display:block;font-size:1.65rem;margin-top:5px}label{display:grid;gap:5px;font-weight:600}input{padding:9px;border:1px solid #bac3cf;border-radius:6px}.charge{background:#059669}.status{min-height:1.5em;font-weight:600}.warning{color:#b45309}.due{color:#b91c1c}.ok{color:#047857}</style></head><body>
<header><nav><a href="/">Home — Drive &amp; Paths</a><a href="/dashboard">Dashboard</a><a href="/battery-management">Battery Management</a></nav></header><main>
<section class="card"><h1>🔋 Motor Battery Management</h1><p>Estimated usage integrates the two drive-motor current sensors. Both Ah and combined wheel distance reset together when a full charge is recorded.</p></section>
<section class="card"><div class="metrics"><div class="metric">Used since charge<strong id="usedAh">—</strong></div><div class="metric">Estimated remaining<strong id="remaining">—</strong></div><div class="metric">Combined wheel travel<strong id="meters">—</strong></div><div class="metric">Last charged<strong id="lastCharged">—</strong></div></div><p id="status" class="status"></p><button id="charged" class="button charge">Battery has just been fully charged</button></section>
<section class="card"><h2>Capacity and return reserve</h2><form id="settings" class="form"><label>Maximum usable capacity (Ah)<input id="capacity" type="number" min="0.1" max="1000" step="0.1" required></label><label>Return to charger at remaining (%)<input id="reserve" type="number" min="0" max="99" step="1" required></label><label>&nbsp;<button class="button" type="submit">Save settings</button></label></form></section>
</main><script>
const $=id=>document.getElementById(id);async function json(url,options){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw new Error(data.error||'request_failed');return data}function render(s){const used=s.usedAhSinceCharge,remaining=Math.max(0,s.maximumCapacityAh-used),percent=100*remaining/s.maximumCapacityAh;$('usedAh').textContent=used.toFixed(3)+' Ah';$('remaining').textContent=remaining.toFixed(2)+' Ah ('+percent.toFixed(1)+'%)';$('meters').textContent=s.combinedWheelMetersSinceCharge.toFixed(0)+' m';$('lastCharged').textContent=s.lastChargedAt?new Date(s.lastChargedAt).toLocaleString():'Not recorded';$('capacity').value=s.maximumCapacityAh;$('reserve').value=s.returnToChargePercent;$('status').className='status '+(s.returnDue?'due':'ok');$('status').textContent=s.returnDue?'Return-to-charge reserve reached.':'Above the configured return reserve.'}async function load(){render(await json('/api/battery-management'))}$('settings').onsubmit=async event=>{event.preventDefault();try{render(await json('/api/battery-management/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({maximumCapacityAh:Number($('capacity').value),returnToChargePercent:Number($('reserve').value)})}))}catch(error){alert(error.message)}};$('charged').onclick=async()=>{if(!confirm('Record a full charge and reset both Ah and distance counters?'))return;try{render(await json('/api/battery-management/charged',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}))}catch(error){alert(error.message)}};load().catch(error=>alert(error.message));setInterval(()=>load().catch(()=>{}),5000);
</script></body></html>`;
}
