export function getMowingRecordsPageHtml(): string {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mowing Records</title>
<style>
:root{font-family:system-ui;color:#172033;background:#f5f7fa}*{box-sizing:border-box}body{margin:0}header{background:#fff;border-bottom:1px solid #dce1e8;padding:14px 20px;position:sticky;top:0;z-index:10}nav{display:flex;gap:10px;flex-wrap:wrap}nav a,.button{border:0;border-radius:7px;padding:9px 13px;background:#2563eb;color:#fff;text-decoration:none;cursor:pointer}.button:disabled{opacity:.55;cursor:wait}main{width:100%;margin:0;padding:20px;display:grid;gap:18px}.card{background:#fff;border:1px solid #dce1e8;border-radius:10px;padding:18px}h1,h2{margin:0 0 12px}.workspace{display:grid;grid-template-columns:minmax(420px,620px) minmax(480px,1fr);gap:18px;align-items:start}.left-column{display:grid;gap:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.definition-picker{margin-bottom:14px;max-width:420px}label{display:grid;gap:5px;font-weight:600}input,select{padding:9px;border:1px solid #bac3cf;border-radius:6px}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{text-align:left;border-bottom:1px solid #e4e8ed;padding:9px}tr[data-definition-id]{cursor:pointer}tr[data-definition-id]:hover,tr[data-definition-id]:focus{background:#eff6ff;outline:2px solid #93c5fd;outline-offset:-2px}.danger{background:#dc2626}.secondary,.cancel{background:#64748b}.status{font-weight:700;margin-top:12px;min-height:1.5em}.error{color:#b91c1c}.due{color:#b91c1c}.ok{color:#047857}.preview-card{position:sticky;top:78px}.preview-wrap{background:#f8fafc;border:1px solid #dce1e8;border-radius:8px;overflow:hidden}canvas{display:block;width:100%;height:auto;aspect-ratio:3/2}.preview-help{color:#667085;margin:0 0 12px}.preview-status{margin-top:10px;font-weight:600}@media(max-width:1000px){.workspace{grid-template-columns:1fr}.preview-card{position:static}}@media(max-width:600px){main{padding:10px}.card{padding:12px}table{font-size:.85rem}}
</style></head><body>
<header><nav aria-label="Main navigation"><a href="/">Home — Drive &amp; Paths</a><a href="/dashboard">Dashboard</a><a href="/turn-tuning">Turn Tuning</a><a href="/drive-tuning">Drive Tuning</a><a href="/segment-testing">Segment Testing</a><a href="/dead-reckoning">Dead Reckoning</a></nav></header>
<main><section class="card"><h1>🌿 Mowing Records</h1><p>Completed mowing history, reusable mowing settings, and blade maintenance.</p></section>
<div class="workspace"><div class="left-column">
<section class="card"><h2>Blade sharpening</h2><form id="maintenanceForm" class="grid"><label>Last sharpened<input id="lastSharpenedAt" type="date" required></label><label>Forward travel before due (m)<input id="sharpeningInterval" type="number" min="1" step="1" required></label><label>&nbsp;<button class="button" type="submit">Save maintenance</button></label><label id="cancelMaintenanceWrap" hidden>&nbsp;<button id="cancelMaintenance" class="button cancel" type="button">Cancel</button></label></form><div id="sharpeningStatus" class="status"></div></section>
<section class="card"><h2>Mowing definitions</h2><p class="preview-help">Choose an area and fine-tune the strip direction and width against the preview before saving.</p><label class="definition-picker">Edit saved definition<select id="definitionPicker"><option value="">Create a new definition</option></select></label><form id="presetForm" class="grid"><label>Definition name<input id="presetName" required></label><label>Area<select id="presetArea" required></select></label><label>Angle (degrees)<input id="presetHeading" type="number" min="0" max="179" step="1" value="0" required></label><label>Width (cm)<input id="presetWidth" type="number" min="10" max="40" step="1" value="30" required></label><label>&nbsp;<button id="saveDefinition" class="button" type="submit">Save definition</button></label><label id="cancelDefinitionWrap" hidden>&nbsp;<button id="cancelDefinition" class="button cancel" type="button">Cancel</button></label><label>&nbsp;<button id="newDefinition" class="button secondary" type="button">New definition</button></label></form><div id="definitionStatus" class="status" role="status" aria-live="polite"></div><table><thead><tr><th>Name</th><th>Area</th><th>Angle</th><th>Width</th><th></th></tr></thead><tbody id="presets"></tbody></table></section>
</div><section class="card preview-card"><h2>Definition preview</h2><p class="preview-help">The green outline is the selected mowing area; blue lines are the generated mowing strips.</p><div class="preview-wrap"><canvas id="previewCanvas" width="900" height="600"></canvas></div><div id="previewStatus" class="preview-status">Choose an area to preview.</div></section></div>
<section class="card"><h2>Completed mowings</h2><table><thead><tr><th>Date</th><th>Area</th><th>Angle</th><th>Width</th></tr></thead><tbody id="history"></tbody></table></section></main>
<script>
const $=selector=>document.querySelector(selector);const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let state;let previewTimer;let previewSequence=0;let editingPresetId='';let maintenanceEditing=false;let definitionEditing=false;
async function json(url,options){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw new Error(data.error||'request_failed');return data}
function setMaintenanceEditing(editing){maintenanceEditing=editing;$('#cancelMaintenanceWrap').hidden=!editing}
function setDefinitionEditing(editing){definitionEditing=editing;$('#cancelDefinitionWrap').hidden=!editing;$('#definitionPicker').disabled=editing;$('#newDefinition').disabled=editing}
function pointCoordinates(point){return {x:Number(point.xMeters),y:Number(point.yMeters)}}
function drawPreview(plan){const canvas=$('#previewCanvas'),ctx=canvas.getContext('2d'),area=Array.isArray(plan.rawAreaPoints)?plan.rawAreaPoints:[];ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#f8fafc';ctx.fillRect(0,0,canvas.width,canvas.height);const all=area.flatMap(point=>{const p=pointCoordinates(point);return Number.isFinite(p.x)&&Number.isFinite(p.y)?[p]:[]});if(!all.length)return;const xs=all.map(p=>p.x),ys=all.map(p=>p.y),padding=42,rangeX=Math.max(...xs)-Math.min(...xs),rangeY=Math.max(...ys)-Math.min(...ys),scale=Math.min((canvas.width-padding*2)/Math.max(rangeX,.5),(canvas.height-padding*2)/Math.max(rangeY,.5)),cx=(Math.min(...xs)+Math.max(...xs))/2,cy=(Math.min(...ys)+Math.max(...ys))/2,toCanvas=point=>{const p=pointCoordinates(point);return{x:canvas.width/2+(p.x-cx)*scale,y:canvas.height/2-(p.y-cy)*scale}};ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();area.forEach((point,index)=>{const p=toCanvas(point);index?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)});if(area.length>2){const p=toCanvas(area[0]);ctx.lineTo(p.x,p.y)}ctx.fillStyle='rgba(16,185,129,.08)';ctx.fill();ctx.strokeStyle='#059669';ctx.lineWidth=4;ctx.stroke();const colours=['rgba(59,130,246,.16)','rgba(16,185,129,.16)','rgba(245,158,11,.16)','rgba(168,85,247,.16)','rgba(236,72,153,.16)'],regions=new Map((plan.regions||[]).map(region=>[region.id,region]));(plan.strips||[]).forEach(strip=>{const region=regions.get(strip.regionId);if(!region)return;const start=toCanvas(strip.start),end=toCanvas(strip.end);ctx.strokeStyle=colours[region.orderIndex%colours.length];ctx.lineWidth=Math.max(8,(plan.stripSpacingMeters||.3)*scale*.8);ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.lineTo(end.x,end.y);ctx.stroke()});ctx.strokeStyle='#2563eb';ctx.lineWidth=3;(plan.strips||[]).forEach(strip=>{const start=toCanvas(strip.start),end=toCanvas(strip.end);ctx.beginPath();ctx.moveTo(start.x,start.y);ctx.lineTo(end.x,end.y);ctx.stroke()})}
async function updatePreview(){clearTimeout(previewTimer);previewTimer=setTimeout(async()=>{const areaName=$('#presetArea').value,headingDeg=Number($('#presetHeading').value),stripSpacingMeters=Number($('#presetWidth').value)/100;if(!areaName||!Number.isFinite(headingDeg)||!Number.isFinite(stripSpacingMeters)||stripSpacingMeters<.1||stripSpacingMeters>.4){$('#previewStatus').textContent='Choose valid area, angle, and width settings.';return}const sequence=++previewSequence;$('#previewStatus').textContent='Generating preview…';try{const plan=await json('/api/mowing-plan/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({areaName,headingDeg,stripSpacingMeters})});if(sequence!==previewSequence)return;drawPreview(plan);$('#previewStatus').textContent=plan.stripCount+' strips at '+Math.round(plan.headingDeg)+'° and '+Math.round(plan.stripSpacingMeters*100)+' cm width.'}catch(error){if(sequence===previewSequence)$('#previewStatus').textContent='Preview failed: '+error.message}},180)}
function selectDefinition(id){setDefinitionEditing(false);editingPresetId=id||'';$('#definitionPicker').value=editingPresetId;const preset=state.presets.find(item=>item.id===editingPresetId);if(preset){$('#presetName').value=preset.name;$('#presetArea').value=preset.areaName;$('#presetHeading').value=String(Math.round(preset.headingDeg));$('#presetWidth').value=String(Math.round(preset.stripWidthMeters*100));$('#saveDefinition').textContent='Update definition';$('#definitionStatus').textContent='Editing “'+preset.name+'”.'}else{$('#presetName').value='';$('#saveDefinition').textContent='Save definition';$('#definitionStatus').textContent='Creating a new definition.'}updatePreview()}
async function load(){
  state=await json('/api/mowing-records');
  const areas=await json('/api/area-perimeters');
  if(!definitionEditing){
    const selected=$('#presetArea').value;
    $('#presetArea').innerHTML=areas.paths.map(a=>'<option value="'+esc(a.name)+'">'+esc(a.name)+'</option>').join('');
    if(selected)$('#presetArea').value=selected;
    $('#definitionPicker').innerHTML='<option value="">Create a new definition</option>'+state.presets.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name)+' — '+esc(p.areaName)+'</option>').join('');
    if(editingPresetId&&!state.presets.some(p=>p.id===editingPresetId))editingPresetId='';
    $('#definitionPicker').value=editingPresetId;
  }
  const m=state.bladeMaintenance;
  if(!maintenanceEditing){
    $('#lastSharpenedAt').value=m.lastSharpenedAt?m.lastSharpenedAt.slice(0,10):'';
    $('#sharpeningInterval').value=m.sharpeningIntervalMeters;
  }
  const travelled=m.metersSinceSharpening,remaining=m.sharpeningIntervalMeters-travelled;
  const s=$('#sharpeningStatus');
  s.className='status '+(remaining<=0?'due':'ok');
  s.textContent=remaining<=0?'Blade sharpening is due ('+Math.round(travelled)+' m of forward motor travel since sharpening).':Math.round(travelled)+' m travelled; '+Math.ceil(remaining)+' m remaining before sharpening is due.';
  $('#presets').innerHTML=state.presets.map(p=>'<tr data-definition-id="'+esc(p.id)+'" tabindex="0" aria-label="Load '+esc(p.name)+' definition preview"><td>'+esc(p.name)+'</td><td>'+esc(p.areaName)+'</td><td>'+Math.round(p.headingDeg)+'°</td><td>'+Math.round(p.stripWidthMeters*100)+' cm</td><td><button class="button secondary" data-edit="'+esc(p.id)+'">Edit</button> <button class="button danger" data-delete="'+esc(p.id)+'">Delete</button></td></tr>').join('')||'<tr><td colspan="5">No definitions saved.</td></tr>';
  $('#history').innerHTML=state.history.map(h=>'<tr><td>'+new Date(h.completedAt).toLocaleString()+'</td><td>'+esc(h.areaName)+'</td><td>'+Math.round(h.headingDeg)+'°</td><td>'+Math.round(h.stripWidthMeters*100)+' cm</td></tr>').join('')||'<tr><td colspan="4">No completed mowings yet.</td></tr>';
  if(!definitionEditing)updatePreview();
}
$('#maintenanceForm').addEventListener('input',()=>setMaintenanceEditing(true));
$('#maintenanceForm').addEventListener('change',()=>setMaintenanceEditing(true));
$('#maintenanceForm').onsubmit=async e=>{e.preventDefault();await json('/api/mowing-records/maintenance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lastSharpenedAt:$('#lastSharpenedAt').value,sharpeningIntervalMeters:Number($('#sharpeningInterval').value)})});setMaintenanceEditing(false);await load()};
$('#cancelMaintenance').onclick=async()=>{setMaintenanceEditing(false);await load()};
$('#presetForm').addEventListener('input',()=>setDefinitionEditing(true));
$('#presetForm').addEventListener('change',()=>setDefinitionEditing(true));
$('#presetForm').onsubmit=async e=>{e.preventDefault();const button=$('#saveDefinition'),status=$('#definitionStatus');button.disabled=true;status.className='status';status.textContent=editingPresetId?'Updating definition…':'Saving definition…';try{const saved=await json('/api/mowing-records/presets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:editingPresetId||undefined,name:$('#presetName').value,areaName:$('#presetArea').value,headingDeg:Number($('#presetHeading').value),stripWidthMeters:Number($('#presetWidth').value)/100})});editingPresetId=saved.id;setDefinitionEditing(false);await load();status.className='status ok';status.textContent='Definition “'+saved.name+'” saved successfully.';button.textContent='Update definition'}catch(error){status.className='status error';status.textContent='Could not save definition: '+error.message}finally{button.disabled=false}};
$('#cancelDefinition').onclick=async()=>{setDefinitionEditing(false);await load();selectDefinition(editingPresetId)};
$('#definitionPicker').onchange=e=>selectDefinition(e.target.value);$('#newDefinition').onclick=()=>selectDefinition('');
$('#presets').onclick=async e=>{if(definitionEditing)return;const editId=e.target.dataset.edit;if(editId){selectDefinition(editId);return}const id=e.target.dataset.delete;if(id){try{await json('/api/mowing-records/presets/delete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id})});if(editingPresetId===id)editingPresetId='';await load();$('#definitionStatus').className='status ok';$('#definitionStatus').textContent='Definition deleted.'}catch(error){$('#definitionStatus').className='status error';$('#definitionStatus').textContent='Could not delete definition: '+error.message}return}const row=e.target.closest('tr[data-definition-id]');if(row)selectDefinition(row.dataset.definitionId)};
$('#presets').onkeydown=e=>{if(definitionEditing)return;if((e.key==='Enter'||e.key===' ')&&e.target.matches('tr[data-definition-id]')){e.preventDefault();selectDefinition(e.target.dataset.definitionId)}};
['#presetArea','#presetHeading','#presetWidth'].forEach(selector=>$(selector).addEventListener('input',updatePreview));load().catch(e=>alert(e.message));
</script></body></html>`;
}
