import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { PrimitivesStore, resolveServerPort, routeServerRequest } from '../dist/index.js';
import { getManualDrivePageCss, getManualDrivePageHtml, getManualDrivePageJs } from '../dist/server/manualDrivePage.js';
import { getTurnTuningPageHtml } from '../dist/server/turnTuningPage.js';
import { getDriveTuningPageHtml } from '../dist/server/driveTuningPage.js';
import { getSegmentTestingPageHtml } from '../dist/server/segmentTestingPage.js';
import { getDeadReckoningPageHtml } from '../dist/server/deadReckoningPage.js';
import { renderPathTracingPage } from '../dist/server/pathTracingPage.js';

test('resolveServerPort returns fallback for invalid values', () => {
  assert.equal(resolveServerPort(undefined, 8090), 8090);
  assert.equal(resolveServerPort('0', 8090), 8090);
  assert.equal(resolveServerPort('abc', 8090), 8090);
  assert.equal(resolveServerPort('8090', 8090), 8090);
});

test('routeServerRequest serves health and primitives payloads', () => {
  const primitives = new PrimitivesStore();

  const healthRoute = routeServerRequest('GET', '/health', 'running', 'mower-core-test', primitives.snapshot(), null, null, null, null, null, null, null, null);
  assert.equal(healthRoute.statusCode, 200);
  const health = JSON.parse(healthRoute.body);
  assert.equal(health.ok, true);
  assert.equal(health.state, 'running');

  const primitivesRoute = routeServerRequest('GET', '/api/primitives', 'running', 'mower-core-test', primitives.snapshot(), null, null, null, null, null, null, null, null);
  assert.equal(primitivesRoute.statusCode, 200);
  const primitivesPayload = JSON.parse(primitivesRoute.body);
  assert.equal(primitivesPayload.state, 'running');
  assert.equal(typeof primitivesPayload.primitives.sampledAt, 'string');
  assert.equal(typeof primitivesPayload.primitives.imu, 'object');
  assert.equal(typeof primitivesPayload.primitives.gnss, 'object');
  assert.equal(typeof primitivesPayload.primitives.poseFusion, 'object');
  assert.equal(typeof primitivesPayload.primitives.poseFusion.usingGnssHeading, 'boolean');
  assert.equal(typeof primitivesPayload.primitives.motors, 'object');
});

test('routeServerRequest serves Drive & Paths as home, dashboard expansion, and 404 responses', () => {
  const primitives = new PrimitivesStore();

  const homeRoute = routeServerRequest('GET', '/', 'running', 'mower-core-test', primitives.snapshot(), null, null, null, null, null, null, null, null);
  assert.equal(homeRoute.statusCode, 200);
  assert.equal(homeRoute.contentType.startsWith('text/html'), true);
  assert.equal(homeRoute.body.includes('Drive & Paths'), true);
  assert.equal(homeRoute.body.includes('id="mapCanvas"'), true);
  assert.equal(homeRoute.body.includes('id="mini-imu-widget"'), true);
  assert.equal(homeRoute.body.includes('id="mini-gnss-widget"'), true);
  assert.equal(homeRoute.body.includes('id="mini-motor-odometry-widget"'), true);
  assert.equal(homeRoute.body.includes('href="/dashboard"'), true);
  assert.equal(homeRoute.body.includes('href="/mowing-records"'), true);
  assert.equal(homeRoute.body.includes('id="mowingPreset"'), true);

  const dashboardRoute = routeServerRequest('GET', '/dashboard', 'running', 'mower-core-test', primitives.snapshot(), null, null, null, null, null, null, null, null);
  assert.equal(dashboardRoute.statusCode, 200);
  assert.equal(dashboardRoute.body.includes('Mower Control Dashboard'), true);
  assert.equal(dashboardRoute.body.includes('<span>Home</span>'), true);
  assert.equal(dashboardRoute.body.includes('href="/"'), true);
  assert.equal(dashboardRoute.body.includes('Segment Testing'), true);
  assert.equal(dashboardRoute.body.includes('id="gnss-sat-warning"'), true);

  const recordsRoute = routeServerRequest('GET', '/mowing-records', 'running', 'mower-core-test', primitives.snapshot(), null, null, null, null, null, null, null, null);
  assert.equal(recordsRoute.statusCode, 200);
  assert.equal(recordsRoute.body.includes('Mowing Records'), true);
  assert.equal(recordsRoute.body.includes('/api/mowing-records/maintenance'), true);
  assert.equal(recordsRoute.body.includes('id="previewCanvas"'), true);
  assert.equal(recordsRoute.body.includes('/api/mowing-plan/preview'), true);
  assert.equal(recordsRoute.body.includes('Mowing definitions'), true);
  assert.equal(recordsRoute.body.includes('id="definitionPicker"'), true);
  assert.equal(recordsRoute.body.includes('id="definitionStatus"'), true);
  assert.equal(recordsRoute.body.includes('Update definition'), true);
  assert.equal(recordsRoute.body.includes('data-definition-id='), true);
  assert.equal(recordsRoute.body.includes("selectDefinition(row.dataset.definitionId)"), true);
  assert.equal(recordsRoute.body.includes("e.key==='Enter'||e.key===' '"), true);

  const manualRoute = routeServerRequest('GET', '/manual-drive', 'running', 'mower-core-test', primitives.snapshot(), null, null, null, null, null, null, null, null);
  assert.equal(manualRoute.statusCode, 200);
  assert.equal(manualRoute.contentType.startsWith('text/html'), true);
  assert.equal(manualRoute.body.includes('Drive & Paths'), true);
  assert.equal(manualRoute.body.includes('id="mapCanvas"'), true);
  assert.equal(manualRoute.body.includes('id="mowingPlanArea"'), true);
  assert.equal(manualRoute.body.includes('id="mowingHeadingDeg"'), true);
  assert.equal(manualRoute.body.includes('id="startRecordingBtn"'), true);
  assert.equal(manualRoute.body.includes('id="startAreaRecordingBtn"'), true);
  assert.equal(manualRoute.body.includes('id="pathsList"'), true);
  assert.equal(manualRoute.body.includes('id="areaPerimetersList"'), true);
  assert.equal(manualRoute.body.includes('id="stopPathBtn"'), true);
  assert.equal(manualRoute.body.includes('Controller Demand'), false);
  assert.equal(manualRoute.body.includes('Motion Feedback'), false);

  const pathRoute = routeServerRequest('GET', '/path-tracing', 'running', 'mower-core-test', primitives.snapshot(), null, null, null, null, null, null, null, null);
  assert.equal(pathRoute.statusCode, 200);
  assert.equal(pathRoute.contentType.startsWith('text/html'), true);
  assert.equal(pathRoute.body, getManualDrivePageHtml());

  const missingRoute = routeServerRequest('GET', '/missing', 'running', 'mower-core-test', primitives.snapshot(), null, null, null, null, null, null, null, null);
  assert.equal(missingRoute.statusCode, 404);
  const missingPayload = JSON.parse(missingRoute.body);
  assert.equal(missingPayload.error, 'not_found');
});

test('tuning pages expose the simplified drive training controls', () => {
  const turnPage = getTurnTuningPageHtml();
  assert.equal(turnPage.includes('class="page-layout"'), true);
  assert.equal(turnPage.includes('class="top-grid"'), true);
  assert.equal(turnPage.includes('class="top-controls"'), true);
  assert.equal(turnPage.includes('class="top-stats"'), true);
  assert.equal(turnPage.includes('class="stats-list"'), true);
  assert.equal(turnPage.includes('class="stats-row"'), true);
  assert.equal(turnPage.includes('class="widget-shell compact-widget"'), true);
  assert.equal(turnPage.includes('id="imu-widget"'), true);
  assert.equal(turnPage.includes('id="gnss-widget"'), true);
  assert.equal(turnPage.includes('id="stopCurrentRun"'), true);
  assert.equal(turnPage.includes('class="center-row"'), true);
  assert.equal(turnPage.includes('class="single-run-panel"'), true);
  assert.equal(turnPage.includes('Turn / Training Start Angle (degrees)'), true);
  assert.equal(turnPage.includes('id="runRealPoseValidation"'), true);
  assert.equal(turnPage.includes('appDialogBackdrop'), true);
  assert.equal(turnPage.includes('Are you sure you want to clear all turn history?'), true);
  assert.equal(turnPage.includes('Are you sure you want to reset turn learning parameters to defaults?'), true);
  assert.equal(turnPage.includes('id="validationResultsTableBody"'), true);
  assert.equal(turnPage.includes('id="validationStatus"'), true);
  assert.equal(turnPage.includes('id="learningDiagnostics"'), true);
  assert.equal(turnPage.includes('id="smallTurnParametersBody"'), true);
  assert.equal(turnPage.includes('id="largeTurnParametersBody"'), true);
  assert.equal(turnPage.includes('Learning Rates'), true);
  assert.equal(turnPage.includes('Small-Angle Buckets'), true);
  assert.equal(turnPage.includes('Large-Angle Buckets'), true);
  assert.equal(turnPage.includes('Mode</th>'), true);
  assert.equal(turnPage.includes('Bucket</th>'), true);
  assert.equal(turnPage.includes('Trigger</th>'), true);
  assert.equal(turnPage.includes('Bias</th>'), false);
  assert.equal(turnPage.includes('CCW Brake Time'), true);
  assert.equal(turnPage.includes('Brake Scalar</th>'), true);
  assert.equal(turnPage.includes('small timeout'), true);
  assert.equal(turnPage.includes('rate × scalar'), true);
  assert.equal(turnPage.includes('function formatControlMode(mode)'), true);
  assert.equal(turnPage.includes('function formatTrigger(result)'), true);
  assert.equal(turnPage.includes('Brake Distance</th>'), false);
  assert.equal(turnPage.includes('renderLearningDiagnostics(data.parameters, data.learningDiagnostics);'), true);
  assert.equal(turnPage.includes('const turnActionButtons = ['), true);
  assert.equal(turnPage.includes('function syncTurnButtons()'), true);
  assert.equal(turnPage.includes("stopButton.disabled = false;"), true);
  assert.equal(turnPage.includes('startAngleDeg'), true);

  const drivePage = getDriveTuningPageHtml();
  assert.equal(drivePage.includes('class="page-layout"'), true);
  assert.equal(drivePage.includes('class="sidebar-column"'), true);
  assert.equal(drivePage.includes('id="imu-status"'), false);
  assert.equal(drivePage.includes('id="gnss-status"'), false);
  assert.equal(drivePage.includes('Distance (cm)'), true);
  assert.equal(drivePage.includes('id="startDriveTuning"'), true);
  assert.equal(drivePage.includes('id="stopDriveTuning"'), true);
  assert.equal(drivePage.includes('id="resetDriveLearning"'), true);
  assert.equal(drivePage.includes('id="startDistanceCm"'), true);
  assert.equal(drivePage.includes('start tuning'), true);
  assert.equal(drivePage.includes('Are you sure you want to reset drive learning parameters to defaults?'), true);
  assert.equal(drivePage.includes('/api/drive/reset-learning'), true);
  assert.equal(drivePage.includes('window.operatorPage.fetchJson("/api/drive/status?ts=" + Date.now())'), true);
  assert.equal(drivePage.includes('maxDistanceMeters: endAtMeters'), true);
  assert.equal(drivePage.includes('const maxDriveResultRows = 500;'), true);
  assert.equal(drivePage.includes('const driveResultRows = [];'), true);
  assert.equal(drivePage.includes('let startHandshakePending = false;'), true);
  assert.equal(drivePage.includes('function syncDriveButtons()'), true);
  assert.equal(drivePage.includes('startButton.disabled = startHandshakePending || trainingActive;'), true);
  assert.equal(drivePage.includes('stopButton.disabled = false;'), true);
  assert.equal(drivePage.includes('appendDriveRows(history);'), true);
  assert.equal(drivePage.includes('appendDriveRows(liveResults);'), true);
  assert.equal(drivePage.includes('driveResultRows.slice(-maxDriveResultRows).reverse()'), true);
  assert.equal(drivePage.includes('Distance</th>'), true);
  assert.equal(drivePage.includes('Avg CTE</th>'), true);
  assert.equal(drivePage.includes('Max CTE</th>'), true);
  assert.equal(drivePage.includes('X Error</th>'), true);
  assert.equal(drivePage.includes('Y Error</th>'), true);

  const segmentPage = getSegmentTestingPageHtml();
  assert.equal(segmentPage.includes('class="page-layout"'), true);
  assert.equal(segmentPage.includes('class="sidebar-column"'), true);
  assert.equal(segmentPage.includes('id="imu-widget"'), true);
  assert.equal(segmentPage.includes('id="gnss-widget"'), true);
  assert.equal(segmentPage.includes('window.operatorPage.fetchJson("/api/primitives?ts=" + Date.now())'), true);
  assert.equal(segmentPage.includes('primitives: primitivesPayload.primitives'), true);
  assert.equal(segmentPage.includes('id="startSegmentTest"'), true);
  assert.equal(segmentPage.includes('id="stopSegmentTest"'), true);
  assert.equal(segmentPage.includes('let segmentStateSnapshot = { phase: "idle", running: false };'), true);
  assert.equal(segmentPage.includes('function syncSegmentButtons()'), true);
  assert.equal(segmentPage.includes('startButton.disabled = startHandshakePending || runActive;'), true);
  assert.equal(segmentPage.includes('stopButton.disabled = false;'), true);
  assert.equal(segmentPage.includes('id="segmentResultsTableBody"'), true);
  assert.equal(segmentPage.includes('Segment Results'), true);
  assert.equal(segmentPage.includes('Run Segment Test'), true);
  assert.equal(segmentPage.includes('Heading Diff</th>'), true);
  assert.equal(segmentPage.includes('formatHeadingDifference(item.requiredHeadingChangeDeg, item.achievedHeadingChangeDeg)'), true);
  assert.equal(segmentPage.includes('colspan="12"'), true);
  assert.equal(segmentPage.includes('Avg CTE (cm)</th>'), true);
  assert.equal(segmentPage.includes('Max CTE (cm)</th>'), true);
  assert.equal(segmentPage.includes('X Error (cm)</th>'), true);
  assert.equal(segmentPage.includes('Y Error (cm)</th>'), true);
  assert.equal(segmentPage.includes('formatCentimeters(item.cteMeters)'), true);

  const manualPageHtml = getManualDrivePageHtml();
  const manualPage = manualPageHtml + getManualDrivePageCss() + getManualDrivePageJs();
  assert.equal(manualPage.includes('Drive & Paths'), true);
  assert.equal(manualPage.includes('id="mapCanvas"'), true);
  assert.equal(manualPage.includes('id="mowingPlanArea"'), true);
  assert.equal(manualPage.includes('id="mowingHeadingDeg"'), true);
  assert.equal(manualPage.includes('id="stripSpacingCm"'), true);
  assert.equal(manualPage.includes('id="mowingPlanStatus"'), true);
  assert.equal(manualPage.includes('id="startMowingNoPerimeterBtn"'), true);
  assert.equal(manualPage.includes('Mow From Perimeter'), true);
  assert.equal(manualPage.includes('id="resumeMowingBtn"'), true);
  assert.equal(manualPage.includes('Carry On Mowing'), true);
  assert.equal(manualPage.includes("const STRIP_SPACING_STORAGE_KEY = 'manualDrivePage.stripSpacingCm';"), true);
  assert.equal(manualPage.includes("const MOWING_PROGRESS_STORAGE_KEY = 'manualDrivePage.mowingProgress';"), true);
  assert.equal(manualPage.includes('clearMowingProgress();'), true);
  assert.equal(manualPage.includes('MAX_HISTORY_MS'), false);
  assert.equal(manualPage.includes("ctx.strokeStyle = 'rgba(37, 99, 235, 0.6)';"), true);
  assert.equal(manualPage.includes('id="startRecordingBtn"'), true);
  assert.equal(manualPage.includes('id="startAreaRecordingBtn"'), true);
  assert.equal(manualPage.includes('id="stopPathBtn"'), true);
  assert.equal(manualPage.includes('id="pathsList"'), true);
  assert.equal(manualPage.includes('id="areaPerimetersList"'), true);
  assert.equal(manualPage.includes('Controller Demand'), false);
  assert.equal(manualPage.includes('Motion Feedback'), false);
  assert.equal(manualPage.includes('appDialogBackdrop'), true);
  assert.equal(manualPage.includes('onclick="verifyPath('), true);
  assert.equal(manualPage.includes('Segmented drive'), false);
  assert.equal(manualPage.includes('/api/path/algorithm'), false);
  assert.equal(manualPage.includes('/api/area-perimeter/algorithm'), false);
  assert.equal(manualPage.includes('/api/path/verify'), true);
  assert.equal(manualPage.includes('/api/area-perimeter/verify'), true);
  assert.equal(manualPage.includes('/api/area-perimeter/drive'), true);
  assert.equal(manualPage.includes('id="perimeterEditorCanvas"'), true);
  assert.equal(manualPage.includes('onclick="editAreaPerimeter('), true);
  assert.equal(manualPage.includes("postJson('/api/area-perimeter/update'"), true);
  assert.equal(manualPage.includes('function replaceShorterPerimeterSection('), true);
  assert.equal(manualPage.includes("perimeterEditorStatus.textContent = 'Corrected mowing area perimeter saved."), true);
  assert.equal(manualPage.includes('await closePerimeterEditor();'), false);
  assert.equal(manualPage.includes('/api/mowing-plan/preview'), true);
  assert.equal(manualPage.includes('/api/mowing/resume'), true);
  assert.equal(manualPage.includes('skipInitialBoundaryTrace: Boolean(skipInitialBoundaryTrace)'), true);
  assert.equal(manualPage.includes('nearest point'), true);
  assert.equal(manualPage.includes('MAP_MIN_VIEW_RANGE_METERS = 5'), true);
  assert.equal(manualPage.includes('MAP_STATIONARY_POINT_SPACING_METERS = 0.03'), true);
  assert.equal(manualPage.includes('const { fetchJson, postJson, stopAll } = window.operatorPage;'), true);
  assert.equal(manualPage.includes('const primitives = data.primitives;'), true);
  assert.equal(manualPage.includes('hasDrawablePathPoints(path)'), true);
  assert.equal(manualPage.includes("fetchJson('/api/paths?includePoints=1')"), true);
  assert.equal(manualPage.includes("fetchJson('/api/area-perimeters?includePoints=1')"), true);
  assert.equal(manualPage.includes('function sanitizeStoredPathCollection(paths, warningLabel)'), true);
  assert.equal(manualPage.includes('function markMowingPlanPreviewStale()'), true);
  assert.equal(manualPage.includes('function schedulePageStatePoll(delayMs = PRIMITIVES_POLL_MS)'), true);
  assert.equal(manualPage.includes('function scheduleListRefresh(delayMs = LIST_REFRESH_MS)'), true);
  assert.equal(manualPage.includes("document.addEventListener('visibilitychange'"), true);
  assert.equal(manualPage.includes("fetchJson('/api/primitives')"), true);
  assert.equal(manualPage.includes('setInterval(updateStatus, 500)'), false);
  assert.equal(manualPage.includes('setInterval(loadStoredPaths, 10000)'), false);
  assert.equal(manualPage.includes('setInterval(loadStoredAreaPerimeters, 10000)'), false);
  assert.equal(manualPage.includes('Skipping ${warningLabel} with invalid points:'), true);
  assert.equal(manualPage.includes("result.failedSegment?.errorMessage"), true);
  assert.equal(manualPage.includes('confirm('), false);

  const deadReckoningPage = getDeadReckoningPageHtml();
  assert.equal(deadReckoningPage.includes('id="lineDistanceMeters"'), true);
  assert.equal(deadReckoningPage.includes('id="arcSweepDegrees"'), true);
  assert.equal(deadReckoningPage.includes('Straight distance'), true);
  assert.equal(deadReckoningPage.includes('Arc sweep'), true);
  assert.equal(deadReckoningPage.includes("window.operatorPage.postJson('/api/dead-reckoning/start', { lineDistanceMeters, arcSweepDegrees })"), true);

  const pathPage = renderPathTracingPage();
  assert.equal(pathPage, manualPageHtml);
});

test('launcher and systemd unit pin logs to the repo logs folder', async () => {
  const repoRoot = process.cwd();
  const launcher = await readFile(join(repoRoot, 'scripts/mower-launch.sh'), 'utf8');
  assert.equal(launcher.includes('export MOWER_LOG_DIR="${MOWER_LOG_DIR:-$REPO_DIR/logs}"'), true);

  const serviceTemplate = await readFile(join(repoRoot, 'systemd/mower.service.template'), 'utf8');
  assert.equal(serviceTemplate.includes('Environment=MOWER_LOG_DIR=__MOWER_REPO_DIR__/logs'), true);
});
