import type { ParameterSet } from "./parameterSchema.js";

export const defaultParameters: ParameterSet = {
  controlLoopHz: 20,
  physicalCuttingWidthMeters: 0.4,
  effectivePlanningStripeWidthMeters: 0.3,
  estimatedLawnAreaSquareMeters: 500,
  wheelBaseMeters: 0.52,
  wheelCircumferenceMeters: 0.7,
  encoderCountsPerWheelRevolution: 1620,
  antennaBaselineMeters: 0.3,
  frontAntennaForwardOfAxleMeters: 0.07,
  maxWheelSpeedMetersPerSecond: 0.75,
  maxWheelAccelerationMetersPerSecondSquared: 0.5,
  maxWheelDecelerationMetersPerSecondSquared: 1.5,
  motorRampUpMillis: 1200,
  motorRampDownMillis: 300,
  leftMotorForwardSign: -1,
  rightMotorForwardSign: -1,
  leftMotorForwardScale: 1.0,
  leftMotorReverseScale: 1.0,
  rightMotorForwardScale: 1.0,
  rightMotorReverseScale: 1.0,
  controllerSteeringSign: 1,
  controllerSpeedSign: 1,
  calibrationTurnScale: 1.0,
  calibrationLineGainScale: 1.0,
  pivotAntennaExcursionMeters: 0.0,
  waypointArrivalToleranceMeters: 0.05,
  headingArrivalToleranceDegrees: 2,
};
