export interface ParameterSet {
  readonly controlLoopHz: number;
  readonly physicalCuttingWidthMeters: number;
  readonly effectivePlanningStripeWidthMeters: number;
  readonly estimatedLawnAreaSquareMeters: number;
  readonly wheelBaseMeters: number;
  readonly wheelCircumferenceMeters: number;
  readonly encoderCountsPerWheelRevolution: number;
  readonly antennaBaselineMeters: number;
  readonly frontAntennaForwardOfAxleMeters: number;
  readonly maxWheelSpeedMetersPerSecond: number;
  readonly maxWheelAccelerationMetersPerSecondSquared: number;
  readonly maxWheelDecelerationMetersPerSecondSquared: number;
  readonly motorRampUpMillis: number;
  readonly motorRampDownMillis: number;
  readonly leftMotorForwardSign: number;
  readonly rightMotorForwardSign: number;
  readonly leftMotorForwardScale: number;
  readonly leftMotorReverseScale: number;
  readonly rightMotorForwardScale: number;
  readonly rightMotorReverseScale: number;
  readonly controllerSteeringSign: number;
  readonly controllerSpeedSign: number;
  readonly calibrationTurnScale: number;
  readonly calibrationLineGainScale: number;
  readonly pivotAntennaExcursionMeters: number;
  readonly waypointArrivalToleranceMeters: number;
  readonly headingArrivalToleranceDegrees: number;
}
